### ISSUE TITLE
Some text becomes unreadable in dark mode

### ISSUE THREAD

**Issue by fAntMP** [marius-sucan/ChurchBellsTower#2]
Hello Marius, 

on the Welcome Screen, some text remains black instead of change to white when dark mode is enabled making it unreadable.
Namely lines 384 and 389 of the ahk script.

I tried to look at how the text colours were changed (since the appname and some other text did change to white) but I really have almost no experience in coding and could not find it.

![AutoHotkey_acBHExMkm9](https://user-images.githubusercontent.com/93125407/163604917-317340b2-eb3a-474b-b86b-35d161065a1b.png)

**Comment by marius-sucan** [comment]
Hello!

Thank you for the report. I will fix it, as soon as possible .

I know how to fix it ;-).

Best regards, Marius.

**Comment by marius-sucan** [comment]
Bug fixed. Thanks a lot.
